# Google App Engine config file
# -----------------------------
# See https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python310
env: standard
service: default

# Set App Engine instance class (defaults to F1)
# See https://cloud.google.com/appengine/docs/standard/#instance_classes
instance_class: F1

handlers:
  - url: /(.*\.(js|css|png|jpg|ico|svg|woff|woff2|ttf|eot|json))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|ico|svg|woff|woff2|ttf|eot|json)$

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
